print('== Cadastro da Escola ==')
nome = input('Digite o nome: ')
print('Bem vindo(a) '+nome)
lazer = input('O que gosta de fazer?')
print(lazer)
cor = input('Qual a cor preferida?')
print('A cor preferida é '+cor)
time = input('Qual o time de futebol?')
print('Time do Coração: '+time)